### ISSUE TITLE
Implementation of Linked List's functions?

### ISSUE THREAD

**Issue by cosmopockets** [ProAlgos/ProAlgos-Cpp#100]

**Comment by detective-sokka** [comment]
hi i would like to work on this

**Comment by cosmopockets** [comment]
awesome, I am currently working on inserting, deleting, and clearing linkedlist's I will update when I can

**Comment by detective-sokka** [comment]
is there anything i need to learn? I am competent at C and C++ and have studied data structures and algorithms

**Comment by faheel** [comment]
Issue #34 is regarding linked lists, so if anyone is interested in submitting a PR for it then please comment on issue #34 regarding your interest or progress, as this issue will be closed as a duplicate.
