### ISSUE TITLE
Linear search

### ISSUE THREAD

**Issue by ankitrai96** [ProAlgos/ProAlgos-Cpp#111]
Hey, I just came across this repository via Hacktoberfest.
It's pretty interesting and I would like to contribute! I saw that there's a very elementary algorithm missing in "Searching" - Linear Search. I was wondering if I could start off by authoring that?

**Comment by faheel** [comment]
@ankitrai96 Thank you for your interest! However, there already are 3 pull requests regarding linear search, so I suggest that you contribute some other algorithms or data structures of your choice.

Good luck! :smiley:

**Comment by MeLlamoArroz** [comment]
Done!! 😄
