### ISSUE TITLE
Trial division

### ISSUE THREAD

**Issue by Andreasrn** [ProAlgos/ProAlgos-Cpp#113]
Hi there, i'd like to contribute by updating the Trial division algorithm for integer factorization.

**Comment by faheel** [comment]
Sure, that'd be great! You can add it as `trial_division.cpp` under `C++/source/number_theory/`

**Comment by MeLlamoArroz** [comment]
Done Trial Division!

**Comment by Andreasrn** [comment]
I wanted to do it :_ I'll look for another one

**Comment by MeLlamoArroz** [comment]
I'm really sorry, but it was 12 days ago so i thought you forgot it.
The algorithm could be implemented in 10 minutes or less.

**Comment by Andreasrn** [comment]
No problem, I was waiting for the answer (which came a few days later) and I thought it was going take even longer.
