### ISSUE TITLE
Heap sort

### ISSUE THREAD

**Issue by Satch97** [ProAlgos/ProAlgos-Cpp#13]
Hey I'm Satchin, a fellow CE student, I noticed there weren't any algorithms in the repo/pull for heapsort and a few other. 

- May I take the task up of adding this? 

- And if there are any others do I just simply create the pull request for each?

**Comment by faheel** [comment]
Yes @Satch97, you are very much welcome to suggest/add algorithms to the repo!

If you want to contribute by adding an implementation of an algorithm, following are a few guidelines you should follow:
 - Comment your code properly! 
 - For programs on sorting, in C++, use the utility functions from [`SortingUtils.h`](../blob/master/Sorting/SortingUtils.h).
 - To get an idea of how the code should be structured, view implementations of [other sorting algorithms](../blob/master/Sorting). Also go through the [C++ Coding Guidelines](../blob/master/C++CodingGuidelines.md) if your implementation is in C++.
 - Create a separate pull request for each algorithm you add.

Good luck :+1:

**Comment by faheel** [comment]
Reopening this since heap sort hasn't still been implemented.

If anyone's interested in taking this up, comment here to let others know.

**Comment by Satch97** [comment]
@faheel Hey, I have updated my heap sort implementation pull request, please review.

**Comment by faheel** [comment]
Closed in #20
