### ISSUE TITLE
Add default values to parameters for sorting functions

### ISSUE THREAD

**Issue by faheel** [ProAlgos/ProAlgos-Cpp#136]
Almost all of the sorting functions in this repository have the parameters `order` and `to_show_state` to which the default values `1` and `false` need to be assigned respectively.

**Comment by alxmjo** [comment]
In my experience default values for parameters are usually added in header files. Since there aren't headers for the sorting files, are you looking for something like like this, with function declarations at the top of the cpp file?

In `bubble_sort.cpp`:

```
#include <iostream>
#include <vector>

#include "sorting/utils.hpp"

using namespace std;

void bubble_sort(vector<int>& values, const int order = 1, const bool to_show_state = false);

void bubble_sort(vector<int>& values, const int order, const bool to_show_state) {
    bool swapped;
    size_t i, j;

...
```

**Comment by faheel** [comment]
Sorry for the late response. The default values for parameters can be added to the function definition itself. There's no need for a separate declaration of the function in this case.

**Comment by alxmjo** [comment]
Got it. Just submitted a PR: #139.
