### ISSUE TITLE
Random Data Structures and Algorithms

### ISSUE THREAD

**Issue by eskeype** [ProAlgos/ProAlgos-Cpp#148]
Hello, I thought it would be nice to add a folder for some random data structures and algorithms, and I would like to contribute to it. We could include things like the Fisher-Yates shuffling algorithm, reservoir sampling algorithms, and efficient implementations of collections with that include a 'get random' function

**Comment by faheel** [comment]
Sure! That'd be great!

**Comment by ankur54** [comment]
Hi!! I would like to contribute to it if the issue is still open!!

**Comment by alxmjo** [comment]
Hey @ankur54. Seems like you're keen to get started. In addition to this issue, which you're welcome to start working on, please take a look at #163. We're currently prioritizing migrating the library from the old scheme (which you see under `master`) to the new (which you see under `reorganise`). It's also a great way to become familiar with the library. If you need a hint about how to go about it, check out #202.
