### ISSUE TITLE
Search algorithms

### ISSUE THREAD

**Issue by asas2016SEC** [ProAlgos/ProAlgos-Cpp#149]
* [ ] Jump search
* [ ] Fibonacci search
* [ ] Exponential search
* [ ] Interpolation search

**Comment by ankur54** [comment]
Hi!! I would like to contribute to it if it is still open!!

**Comment by faheel** [comment]
@ankur54 None of the above mentioned algorithms have been implemented yet, so you can give it a go.

**Comment by karwashivani** [comment]
I would like to work on Fibonacci Search if its still open

**Comment by imraniac** [comment]
I would like to contribute if its open.

**Comment by faheel** [comment]
None of the search algorithms mentioned here have been implemented yet (except in #150 which wasn't merged), so contributions are welcome.
