### ISSUE TITLE
Dijkstra Algorithm

### ISSUE THREAD

**Issue by DionisioII** [ProAlgos/ProAlgos-Cpp#151]
I would like to add an implementation of the Dijkstra algorithm.

input: path to a txt file as a command line argument. The txt file will contain the data matrix for  distances between nodes(the [i,j] element will represent distance from i to j).

program asks user for source node.

output: distance and path from source node to every other node in the graph.

Let me know if I can work on this

**Comment by ankur54** [comment]
Hi!! I would like to contribute to this issue if it is still open!!
