### ISSUE TITLE
Longest Increasing Subsequence

### ISSUE THREAD

**Issue by hijajoo** [ProAlgos/ProAlgos-Cpp#153]
I would like to do an implementation of Longest Increasing Subsequence in C++.
Problem statement:
Given an unsorted array of integers, return the longest increasing subsequence.

**Comment by shikherjaiswal** [comment]
I would like to work on this issue @hijajoo  @faheel

**Comment by alxmjo** [comment]
Thanks for your interest! Please read our [contribution guidelines](https://github.com/faheel/Algos/blob/master/CONTRIBUTING.md) before you start writing the code. Once you've done that, you can add the code in a header file named `longest_increasing_subsequence.hpp` under `C++/include/algorithm/dynamic_programming/`. In addition, please add unit tests named `longest_increasing_subsequence.cpp` verifying the accuracy of your implementation under `C++/test/algorithm/dynamic_programming/`. Finally, make sure that you're pulling against the `reorganise` branch.

If you get stuck somewhere, or need some clarification on a topic, feel free to ask questions here or on Gitter.
