### ISSUE TITLE
Topological Sort

### ISSUE THREAD

**Issue by cheikhSall** [ProAlgos/ProAlgos-Cpp#160]
Hi,
I would like to do an implementation of Topological short in C++. 
enter :  a directed graph (  template vector ).
exit :  a linear ordering of its vertices .
thanks.

**Comment by alxmjo** [comment]
Hi @cheikhSall. Are you still interested in implementing this?

**Comment by ankur54** [comment]
Hello!! I would like to contribute to this issue!!
