### ISSUE TITLE
Minimax Algorithm

### ISSUE THREAD

**Issue by kcw9796** [ProAlgos/ProAlgos-Cpp#162]
I don't see any minimax algorithm with alpha beta pruning for solving adversarial search like winning tic tac toe. Can I add this algorithm?

**Comment by faheel** [comment]
Sure! You can add related code for it in `C++/include/game_theory/minimax.hpp`, and unit tests in `C++/test/game_theory/minimax.test.cpp`.

**Comment by ankur54** [comment]
Hey! Is this issue still active? I would like to contribute
