### ISSUE TITLE
Reorganise C++ code into header files

### ISSUE THREAD

**Issue by faheel** [ProAlgos/ProAlgos-Cpp#163]
In order to maximise code reuse, it would be better to organise all C++ code into header files. This would allow one to include code from one file, say for `quicksort()`, and use in another file without reimplementing it again. This is not possible for most of the code now since it exists in `.cpp` files having a `main()` function, and so cannot be included in other files as the `main()` gets included as well.

This will also encourage writing unit tests for the headers because due to the absence of a `main()` function, the only other way to check that the code compiles and runs properly is to write a unit test for with a few cases and check that the result is as expected.

**Comment by faheel** [comment]
This task is currently ongoing on the [`reorganise` branch](https://github.com/faheel/Algos/tree/reorganise).

**Comment by ankur54** [comment]
I'm interested to work in this issue!! Thus, please explain it!!

**Comment by alxmjo** [comment]
Hey @ankur54, thanks for your interest. 

Basically, all the algorithms will move into `include/algorithm/<type of algorithm>/<filename>.hpp` (if it's a data structure, it will move into `include/data_structure/<filename>.hpp`). And then corresponding unit tests which actually execute that algorithm will be either moved to or created in the corresponding `test` folder, i.e., `test/algorithm/<type of algorithm>/<filename>.cpp`. Each header file should have one unit test file and vice versa.

Let me know if you have any questions.

**Comment by ankur54** [comment]
Ok so, I need to create both the header (.hpp) file and the unit test file and include both of them in the include folder. Is that right?

**Comment by ankur54** [comment]
What about Random Algorithm and data structures?

**Comment by alxmjo** [comment]
@ankur54 Header goes in `/include` and unit tests (as `.cpp` file) go in `/test`. #202 will show you how it all ends up. Same goes for data structures, etc.
