### ISSUE TITLE
String split function

### ISSUE THREAD

**Issue by youteekarsh** [ProAlgos/ProAlgos-Cpp#164]
Hello Sir

The program will breakdown an input sentence into words and store the separate words in an array of strings. This function comes predefined in some high level languages.

**Comment by faheel** [comment]
Sure. You can use the `std::string::substr()` method and create a wrapper function (named `splice()` for example) that passes the right arguments to it. For example:
```c++
std::string some_str = splice("abcdefgh", 2, 6);    // some_str = "cdef"
```
This can be implemented under `C++/include/algorithm/string/utils.hpp`.

**Comment by youteekarsh** [comment]
Thankyou Sir 

I will implement this program by this week following all the contribution guidelines.

**Comment by faheel** [comment]
@youteekarsh Sorry for my misinterpretation of what you wanted to implement. I mistook it to be a function that does the same thing as `string[start:end]` would do in Python, but I now understand that it would return a list of strings that were separated by a given delimiter in the original string, the same way as `string.split(delimiter)` works in Python.

**Comment by ankur54** [comment]
Is this issue still open? I would like to contribute to it!!

**Comment by youteekarsh** [comment]
I am not sure, faheel is the owner of this project he will confirm this.
