### ISSUE TITLE
Lowest Common Ancestor

### ISSUE THREAD

**Issue by chamow97** [ProAlgos/ProAlgos-Cpp#167]
It would be great if there is Lowest Common Ancestor Algorithm in the repository.

**Comment by camilne** [comment]
I can implement this for a BST. Also, see #154.

**Comment by chamow97** [comment]
I have a code ready. So, can I directly give PR?

**Comment by camilne** [comment]
See #169

**Comment by chamow97** [comment]
That is just for BST I guess.
