### ISSUE TITLE
Adding more dynamic programming algorithms

### ISSUE THREAD

**Issue by heisenberg-2505** [ProAlgos/ProAlgos-Cpp#174]
Adding more famous dynamic programming problems like the Knapsack problem.

**Comment by faheel** [comment]
@heisenberg-2505 Sure, go ahead! Make sure to read the [contribution guidelines](https://github.com/faheel/Algos/blob/master/CONTRIBUTING.md) first, and then you can add either the 0/1 knapsack (in `0_1_knapsack.hpp`) or unbounded knapsack (in `unbounded_knapsack.hpp`), or both, under `C++/include/algorithm/dynamic_programming`. 

Whichever you decide to add, please open a new issue for each one and mention it in your PR's description (separate PRs too for each algorithm). This would make it easy in tracking the progress.

**Comment by heisenberg-2505** [comment]
Okay.

**Comment by heisenberg-2505** [comment]
The path you have mentioned is not yet in the project. Should I create the directory?
Or should I add the file at `C++/source/dynamic_programming`

**Comment by faheel** [comment]
You can create the directory `C++/include/algorithm/dynamic_programming` if it doesn't exist.

**Comment by faheel** [comment]
Moving this conversation to #188.
