### ISSUE TITLE
Fibonacci Number Alg

### ISSUE THREAD

**Issue by sms7182** [ProAlgos/ProAlgos-Cpp#176]
hi 
i don't see Fibonacci Algorithm ,do you want add Fibonacci Algorithm?

**Comment by sms7182** [comment]
if any other algorithm you want please tell i want implement ,

**Comment by faheel** [comment]
Hi @sms7182, thank you for your interest in contributing to Algos. There are 2 implementations of Fibonacci currently in [`C++/source/number_theory`](https://github.com/faheel/Algos/tree/master/C%2B%2B/source/number_theory).

If you'd like to implement other algorithms, then you can open a new issue for those.

**Comment by sms7182** [comment]
yes i like to implement please help me for implement ,so i need  you say that what to do.please tell me
