### ISSUE TITLE
array, linked list, graph and tree algorithms

### ISSUE THREAD

**Issue by hkhojasteh** [ProAlgos/ProAlgos-Cpp#177]
I would like to do some implementation of the array, linked list, graph and tree algorithms in C++ as follows:
1. Sparse Matrix Multiplication algorithm
2. Polynomial multiplication using linked list
3. AVL (Adelson-Velskii and Landis) tree
4. Bellman–Ford
5. Prim Minimum Spanning Tree
6. Kruskal Minimum Spanning Tree
7. Salin Minimum Spanning Tree
*. Bucket sort

**Comment by faheel** [comment]
Hey @hkhojasteh! Thanks for separating your PRs. Can you also please close this issue and open new ones that are specific to a single algorithm or data structure? It would be a huge help in tracking progress of what's been done and what still remains to be done.

P.S. I'll review your PRs soon, sorry for the delay.
