### ISSUE TITLE
Doubly linked list

### ISSUE THREAD

**Issue by korrat** [ProAlgos/ProAlgos-Cpp#187]
There doesn't seem to be a doubly linked list here.
Can I add one?

**Comment by faheel** [comment]
@korrat Thanks for your interest! Please read our [contribution guidelines](https://github.com/faheel/Algos/blob/master/CONTRIBUTING.md) before you start writing the code. Once you've done that, you can add the code in a header file named `doubly_linked_list.hpp` under `C++/include/data_structures/linked_list`. If you get stuck somewhere, or need some clarification on a topic, feel free to ask questions here or on Gitter in the [data structures room](https://gitter.im/Algos-f/Data-structures).

**Comment by ankur54** [comment]
Is this issue still open? I would like to contribute to it!!

**Comment by michan94** [comment]
Hi there, I'd like to take on this issue if it's still available. Thanks
