### ISSUE TITLE
The 0-1 Knapsack Problem.

### ISSUE THREAD

**Issue by heisenberg-2505** [ProAlgos/ProAlgos-Cpp#188]
I would like to add the 0-1 Knapsack problem, a very famous Dynamic Programming algorithm.

**Comment by faheel** [comment]
@heisenberg-2505 I have assigned this issue to you. Whenever you're done with the implementation, please submit a PR for it against the `reorganise` branch along with a [unit test](https://github.com/faheel/Algos/blob/reorganise/C%2B%2B/UNIT_TESTS.md).

**Comment by heisenberg-2505** [comment]
Should I create a cpp file only or also create a hpp file as you mentioned before?

**Comment by alxmjo** [comment]
The `.hpp` file will be the algorithm, and the `.cpp` file (in the `test` directory) will be the unit test.

**Comment by heisenberg-2505** [comment]
I have written the unit test but the make file is not running/compiling my unit test file.
The code in my test file is - 

`#define KNAPSACK_TEST`
`#include "third_party/catch.hpp"`
`#include "algorithms/dynamic_programming/0_1_knapsack.hpp"`
`TEST_CASE("BASE CASES", "[knapsack]") {
  REQUIRE(knapsack (10, 3, [11, 21, 31], [1, 2, 3]) == 0);
}`
`#undef KNAPSACK_TEST`

**Comment by heisenberg-2505** [comment]
Do we need to make changes to some other file to make this work?

**Comment by alxmjo** [comment]
I don't have my laptop with me so will have to answer your question later regarding compilation, but have you tried compiling using CMake? There are several examples in `CMakeLists.txt` of how to compile the unit test files.

**Comment by heisenberg-2505** [comment]
Where is the file you mentioned above, is located?

**Comment by faheel** [comment]
Closed in #191.
