### ISSUE TITLE
Kadane's Algorithm

### ISSUE THREAD

**Issue by ambuj-gahoi** [ProAlgos/ProAlgos-Cpp#190]

**Comment by ambuj-gahoi** [comment]
I would like to add Kadane's Algorithm for maximum subarray sum problem. It is a famous dynamic programming algorithm.

**Comment by alxmjo** [comment]
Thanks for your interest! Kadane's is already implemented [here](https://github.com/faheel/Algos/blob/master/C%2B%2B/source/maximum_subarray/kadane.cpp). How about refactoring it into an `.hpp` file as part of the reorganise effort? More details in #163.
