### ISSUE TITLE
Contribution Guidelines out of sync between master and reorganise branches

### ISSUE THREAD

**Issue by alxmjo** [ProAlgos/ProAlgos-Cpp#192]
The Contribution Guidelines on the `reorganise` branch are inaccurate (they reference the wrong branch). They should reflect the (more up to date) Contribution Guidelines on the `master` branch. 

Eventually they'll be merged into one, but this will prevent confusion in the interim.

**Comment by heisenberg-2505** [comment]
Hi, can I take this issue up?

**Comment by alxmjo** [comment]
@heisenberg-2505 Please do! Let us know if you have any questions.

**Comment by heisenberg-2505** [comment]
To be clear, I only need to change the readme for the reorganise branch?

**Comment by alxmjo** [comment]
Yep. Reorganise branch should say that we're currently working out of the reorganise branch, rather than master.

**Comment by faheel** [comment]
Fixed in 2da9bebde2539b4a805ca4be11b9cbb67bb8fa7f.
