### ISSUE TITLE
Shunting Yard Algorithm

### ISSUE THREAD

**Issue by DevRin** [ProAlgos/ProAlgos-Cpp#195]
I was wondering if you wanted to add Shunting-yard algorithm. If yes, I can do it.

**Comment by alxmjo** [comment]
Definitely, and thanks for your interest! Please read our [contribution guidelines](https://github.com/faheel/Algos/blob/master/CONTRIBUTING.md) before you start coding. 

You can add the code in `shunting_yard.hpp` under `C++/include/algorithm/string` and the unit tests in `shunting_yard.cpp` under `C++/test/algorithm/string`. Note that we're currently working in the `reorganise` branch, so please make sure that you're pulling from and making PRs against that branch.

If you get stuck somewhere, or need some clarification on a topic, feel free to ask questions here or on Gitter.
