### ISSUE TITLE
Basic BigInteger class to handle big numbers of arbitrary length

### ISSUE THREAD

**Issue by faheel** [ProAlgos/ProAlgos-Cpp#21]
Create a data structure that can handle numbers of arbitrary length by writing a `BigInteger` class that supports the following basic mathematical functions:
- add
- subtract
- multiply
- divide
- modulo

by overloading existing operators for each function (`+`, `-`, `*`, `/`, `%`)

The class should also use overloaded `>>` and `<<` operators to get input from the standard input stream (`std::cin`) and to write output to the standard output stream (`std::cout`) respectively.

The path for the file that contains the class should be `DataStructures/BigInteger/BigInteger.hpp`

**Comment by siaswar** [comment]
Is there will be BigFloat or just BigInteger?

**Comment by faheel** [comment]
Since this task was difficult to take on by beginners, and also since there wasn't any progress on it either, I have implemented the class and have written code for overloaded:
- constructors,
- assignment operators,
- relational operators, and
- I/O stream operators.

You can take a look at the progress made so far on the **`dev`** branch [here](../blob/dev/DataStructures/BigInteger).

What remains to be done is to write code for the overloaded arithmetic operators (`+`, `-`, `*`, `/`, `%`), arithmetic-assignment operators (`+=`, `-=`, `*=`, `/=`, `%=`), and unary operators (`++` and `--`, both pre and post).

**Comment by seanhouser** [comment]
I actually had begun work on this a few days before you posted your implementation! I have used a stack-based approach and implemented `>>, <<, +, *, >, <, ==` operators in my own file that I planned to submit with my first ever pull request. Would you be interested in me submitting my stack-based approach alongside your implementation? I'll also be interested in completing your implementation.

**Comment by faheel** [comment]
> I actually had begun work on this a few days before you posted your implementation!

You should have commented on the issue letting others know that you've started working on it.

> Would you be interested in me submitting my stack-based approach alongside your implementation?

Can you share a [gist](https://gist.github.com) of your implementation so that I can have a look at it and then decide what to do?

**Comment by seanhouser** [comment]
> You should have commented on the issue letting others know that you've started working on it.

Of course you're right, lesson learned. This is my first experience with contributing to an open source project, I appreciate your patience and assistance. I'll be happy to share the code I have so far. 
[gist](https://gist.github.com/seanhouser/dd601e4ec1a280c1658d6a8eaeddb255)

**Comment by faheel** [comment]
Your stack-based approach seems to be a bit complicated to me. A string or array based approach is easier to understand as well as to implement. Also, there will be some operations that would take constant time to run when implemented using a string/array based approach, whereas it would take the same operation linear or logarithmic time to run when implemented using a stack-based approach.

For example, compare the code for a stack-based approach and a string-based approach for the following operators:

- `>`

  Stack-based:
  ```C++
  bool BigInteger::operator > ( const BigInteger& a ) {
	if (this->numStack.size() > a.numStack.size())
		return true;
	else if (this->numStack.size() < a.numStack.size())
		return false;
	else if (this->numStack.size() == a.numStack.size()) {
		std::stack<char> lhs = this->numStack;
		std::stack<char> rhs = a.numStack;
		char leftOperand, rightOperand;
		while (!lhs.empty()) {
			leftOperand = lhs.top();
			lhs.pop();
		}
		while (!rhs.empty()) {
			rightOperand = rhs.top();
			rhs.pop();
		}
		if (leftOperand > rightOperand)
			return true;
		else
			return false;
	}
  }
  ```
  
  String-based:
  ```C++
  bool BigInt::operator>(const BigInt& num) {
    if (sign == num.sign)
        return (value > num.value);
    else
        return (sign == '+');
  }
  ```
- `==`

  Stack-based:
  ```C++
  bool BigInteger::operator == (const BigInteger& a ) {
	bool result;
	std::stack<char> lhs = this->numStack;
	std::stack<char> rhs = a.numStack;
	if (lhs.size() != rhs.size())
		result = false;
	else {
		result = true;
		for (int i=0; i<lhs.size(); ++i) {
			if (lhs.top() != rhs.top())
				result = false;
			lhs.pop();
			rhs.pop();
		}
	}
	return result;
  }
  ```

  String-based:
  ```C++
  bool BigInt::operator==(const BigInt& num) {
    if (sign == num.sign)
        return (value > num.value);

    return false;
  }
  ```

**Comment by seanhouser** [comment]
Thank you for the feedback! I completely agree, I thought a stack-based approach would result in better time complexity but your string-based is clearly better for readability and performance. There are other problems with my approach, even as complex as my existing code is a complete implementation would be even more complex, as my code doesn't yet account for negative numbers. 

I would like to abandon the code I have and take on your approach. I'm still learning GitHub and how best to contribute, is it alright to submit pull requests as I make progress, or do you prefer only one pull request once I have the entire project completed? I'm looking forward to getting started, and thank you again!

**Comment by faheel** [comment]
I suggest that you:

1. Create a branch in your fork (make sure the branch is made from the `dev` branch and not `master`)
2. Make some changes
3. Commit your changes and push them to GitHub
4. Create a pull request from that branch comparing it with the `dev` branch (not `master`)

After that you can continue making related changes to that branch, which will be automatically added to your pull request.

**Comment by seanhouser** [comment]
Thank you for the instructions, I believe I have completed them accurately. I will now begin work on the BigInt class, thank you for helping me get setup, the experience was invaluable. 

So that I understand correctly, when I push commits from my branch (named "dev-BigInt"), they are automatically added to my Pull Request. At any point you can view my Pull Request with my latest commit and accept the Pull Request into your fork. Is my understanding of the process correct? Thanks again for all your help.

**Comment by faheel** [comment]
Yes, that's right.

**Comment by arielyyz** [comment]
Hi I also started to work on it. I think you are using wrong logic for relational operators, when you compare "value" with  ">" it compares the strings in lexicographical order and does not compare numbers. May I make a Pull Request?

**Comment by faheel** [comment]
It works fine because lexicographical comparison is an operation with the following properties:
- Two ranges are compared element by element.
- The first mismatching element defines which range is lexicographically less or greater than the other.
- If one range is a prefix of another, the shorter range is lexicographically less than the other.
- If two ranges have equivalent elements and are of the same length, then the ranges are lexicographically equal.
- An empty range is lexicographically less than any non-empty range.
- Two empty ranges are lexicographically equal.

You can check it for different cases [here](http://ideone.com/NoE1QD). In case you find any case for which lexicographic comparison gives a wrong result, do let me know.

**Comment by faheel** [comment]
@arielyyz Yes, you're right. Thanks for pointing this out!

And sure, you can make a pull request to fix this.

**Comment by seanhouser** [comment]
I'm nearly done with this addition, @faheel would you mind assigning this Issue to me and/or removing the up-for-grabs tag?

**Comment by faheel** [comment]
Will do :+1:

**Comment by faheel** [comment]
Issue #74 is now closed

**Comment by faheel** [comment]
This issue lead to the creation of a library! Check out https://github.com/faheel/BigInt
