### ISSUE TITLE
Edit Distance algorithm. [Dynamic Programming]

### ISSUE THREAD

**Issue by probablyangg** [ProAlgos/ProAlgos-Cpp#210]
I'd like to implement the edit distance algorithm between two strings.
[The minimum number of operations (insertions, deletions and substitutions of symbols) to transform one string to another.]
**Input:** two lines of input containing strings (latin characters)
**Output:** edit distance between the two strings.

**Comment by faheel** [comment]
@angelgilhotra I just noticed that edit distance has already been implemented. You can contribute some other algorithm if you'd like.

**Comment by faheel** [comment]
@angelagilhotra I just noticed that edit distance has already been implemented. You can contribute some other algorithm if you'd like.

**Comment by probablyangg** [comment]
@faheel oh, my bad! I must've missed it. Could I do the dynamic programming implementation of Lowest Common Subsequence of two sequences?
