### ISSUE TITLE
Square and multiply for fast exponentiation

### ISSUE THREAD

**Issue by apoorva-mk** [ProAlgos/ProAlgos-Cpp#225]
How about square and multiply technique for fast exponentiation

**Comment by alxmjo** [comment]
Can you elaborate a bit on how you'd like to go about this? Which algorithm would you use?

**Comment by ghost** [comment]
It's probably the one called Al-Khwarizmi Multiplication Algorithm

**Comment by apoorva-mk** [comment]
Hi, it's the implementation of fast modular exponentiation. https://en.wikipedia.org/wiki/Exponentiation_by_squaring. But I believe it has already been implemented.

**Comment by faheel** [comment]
@apoorva-mk Yep, it's already implemented. Feel free to suggest any other algorithm or data structure to add.
