### ISSUE TITLE
Measure code coverage

### ISSUE THREAD

**Issue by faheel** [ProAlgos/ProAlgos-Cpp#257]

**Comment by mohsensafari** [comment]
Hi, what kind of reports should be generated? I can do it with gcov, it generates some html reports. is that ok?

**Comment by faheel** [comment]
The coverage data obtained from gcov (or lcov) during the CI build needs to be uploaded to a code coverage service like [Codecov](https://codecov.io) which will generate the reports.

For reference, take a look at an example project with such a setup: [codecov/**example-cpp11-cmake**](https://github.com/codecov/example-cpp11-cmake)
