### ISSUE TITLE
String Processing Algorithms

### ISSUE THREAD

**Issue by cssartori** [ProAlgos/ProAlgos-Cpp#26]
Hi,
What about String Processing Algorithms, such as the classic Knuth-Morris-Pratt (KMP) and the Needleman-Wunsch? Can I work on those to add to the project?

**Comment by faheel** [comment]
Yes, absolutely!

You can create a directory named `String` and add them there.

**Comment by cssartori** [comment]
Nice, will do it :)

**Comment by faheel** [comment]
Closed in #27.
