### ISSUE TITLE
Accept a function as a parameter for ternary search 

### ISSUE THREAD

**Issue by faheel** [ProAlgos/ProAlgos-Cpp#261]
The way ternary search works now is that it takes in a unimodal array and the pattern that the elements in it follow (do they first increase then decrease or do they first decrease then increase) and then returns either the largest or the smallest value in the array (depending on the pattern).

A more general implementation for ternary would be like the one mentioned on [Wikipedia](https://en.wikipedia.org/wiki/Ternary_search#Algorithm) (and elsewhere too) that takes in the unimodal function `func` for which we want to find out the largest or smallest value in the given domain, along with the bounds of the domain, `start` and `end`.

It would be nice to have an overloaded definition for `ternary_search` that implemented this behaviour.

**Comment by sylvaus** [comment]
I would love to take this issue

**Comment by alxmjo** [comment]
@sylvaus It's yours!
