### ISSUE TITLE
Find kth smallest number in an array

### ISSUE THREAD

**Issue by aidan-lane** [ProAlgos/ProAlgos-Cpp#269]
Uses quick sort in O(1) space to find the kth smallest number in an array using divide and conquer approach.

**Comment by mgroovyank** [comment]
Can I take up this issue? @alxmjo @faheel

**Comment by kstavrat** [comment]
Would it be alright if I helped as well? @alxmjo @faheel

**Comment by haidtang** [comment]
Is there anyone working on it?
Can I take it? @alxmjo @faheel

**Comment by alxmjo** [comment]
@haidtang Do it! 🙂
