### ISSUE TITLE
Bit Manipulation algorithms 

### ISSUE THREAD

**Issue by seanhouser** [ProAlgos/ProAlgos-Cpp#28]
I would like to implement bit manipulation algorithms, is this something that would fit well with your project? If so, let me know how you would like the files organized and I'll be happy to get started!

**Comment by faheel** [comment]
A "bit-manipulation algorithm" would be something that simply does bit-manipulation -- just as a sorting algorithm does sorting, and a searching algorithm does searching. But bit-manipulation ... is just bit-manipulation (left-shift, right-shift, XOR etc.). I don't think what an algorithm for bit-manipulation would help achieve. 

In case you were thinking of algorithms that use bit-manipulation techniques heavily to perform some "task", then you can add them in the folder for that "task" (like `Backtracking`, `NumberTheory` etc.).

**Comment by seanhouser** [comment]
Ok, thanks for the feedback.
