### ISSUE TITLE
Various tree data structures and related algorithms

### ISSUE THREAD

**Issue by vaibhav2903** [ProAlgos/ProAlgos-Cpp#32]
Algorithms on Trees, Union Find, Heaps,Maps,Hashing

**Comment by faheel** [comment]
Sure! Can you mention some specific ones so that I or someone else can get started on those?

**Comment by vaibhav2903** [comment]
Binary Search Tree: Traversals(recursion and non-recursion) , Insertion, Deletion 
AVL Tree: Traversals: (recursion and non-recursion) , Insertion, Deletion 
Red Black Trees: Traversals(recursion and non-recursion) , Insertion, Deletion, left Rotate, Right Rotate. 
#note I can contribute if you would like me to.

**Comment by faheel** [comment]
Thanks for the info. And sure, you can contribute.

For each algorithm that you want to add, create a separate issue mentioning that you are working on that, and when you open a pull request, mention the issue number in its description.

**Comment by faheel** [comment]
Closing this issue as it is too broad. There are now separate issues for each type of tree, and also other data structures. Related conversation may follow there.
