### ISSUE TITLE
Fix broken links in readme algorithm list

### ISSUE THREAD

**Issue by alxmjo** [ProAlgos/ProAlgos-Cpp#334]
Many of the links to specific algorithms in the [readme](https://github.com/ProAlgos/ProAlgos-Cpp/tree/master/C%2B%2B) are broken. It appears to mostly be sorting algorithms.

- [ ] Check that links direct to appropriate algorithm implementation (which will be a header file ending in `.hpp`).
- [ ] Fix broken links.

**Comment by a-moreira** [comment]
I'll do that!

**Comment by alxmjo** [comment]
It's yours. Thanks!
