### ISSUE TITLE
Add array's algorithm 

### ISSUE THREAD

**Issue by beardbytes** [ProAlgos/ProAlgos-Cpp#339]
I can post one algorithm per week .

**Comment by alxmjo** [comment]
Great! Be sure to read our [contribution guidelines](https://github.com/ProAlgos/ProAlgos-Cpp/blob/master/.github/CONTRIBUTING.md).

**Comment by beardbytes** [comment]
> Great! Be sure to read our [contribution guidelines](https://github.com/ProAlgos/ProAlgos-Cpp/blob/master/.github/CONTRIBUTING.md).

Sure .
