### ISSUE TITLE
Linked list

### ISSUE THREAD

**Issue by tuckerpo** [ProAlgos/ProAlgos-Cpp#34]
Hello, I could add a template LinkedList I made some time ago for my Data Structures and Algs class, updated for C++11 of course. It would require adding both a .cpp and an interface file if that's alright.

**Comment by nityanandagohain** [comment]
I would also like to contribute

**Comment by psarvesh** [comment]
@faheel 
Is this under works? I don't see the pull request for this. 
If this is not under development by anyone, I can start working on this.

**Comment by faheel** [comment]
@psarvesh There's no active PR for this as of now, so you can definitely contribute.

**Comment by psarvesh** [comment]
@faheel Great. I am writing the code under Algos/C++/include/data_structures/ directory.

**Comment by faheel** [comment]
Closed in commit ddf43b227e7301d3afef6df28f75c0e6cc6fecf6.
