### ISSUE TITLE
Command make all does not work

### ISSUE THREAD

**Issue by alxmjo** [ProAlgos/ProAlgos-Cpp#344]
[README.md](https://github.com/ProAlgos/ProAlgos-Cpp/blob/42060df5388e99bd8ab3dfaaa4afef67358fe288/C%2B%2B/README.md) in the `C++` directory gives the following directions for building: 

> To compile the source files, run **`make all`**.

However, when I download a fresh copy of the repo and run the command, I see the following:

```
alex ProAlgos-Cpp-master $ cd C++
alex C++ $ make all
make: *** No rule to make target `all'.  Stop.
```

Running `make` and `make default` both appear to have the desired effect. So, I think we should either update the `Makefile` or update `README.md` so that the directions are accurate.

Tagging @faheel since he originally set up CMake on the project.

**Comment by faheel** [comment]
Good catch! The `make all` command is from the time before I was using CMake. It was removed [here](https://github.com/ProAlgos/ProAlgos-Cpp/commit/0afe13cd72717b9c38495f204382a61c9ed8893d#diff-9c82112efcbd716213ae3d446a5e6474L45-L46) but the documentation wasn't updated then.

**Comment by faheel** [comment]
Most of the the "Compiling" section in the documentation seems outdated now. It would be better to rewrite it completely, keeping in mind how the compilation process happens now using CMake and also how the Makefile helps in the process (by acting as a "helper script").

**Comment by alxmjo** [comment]
I've just always run `make` and then `make test` whenever I wanted to run all tests. Is there a better way?
