### ISSUE TITLE
Implement Queue Data Structure

### ISSUE THREAD

**Issue by hafraz07** [ProAlgos/ProAlgos-Cpp#363]
Just wanted to add the implementation of a queue.

**Comment by Yash-Thakare22** [comment]
I wanted to work on this issue in C++

**Comment by alxmjo** [comment]
Hi @YashThakare. Hafraz has already implemented this – I just haven't had time to review it yet. Perhaps there's something else you'd like to contribute?

**Comment by Yash-Thakare22** [comment]
@alxmjo I would to like to contribute in any domain. Please assign me some task
