### ISSUE TITLE
Automate unit test execution

### ISSUE THREAD

**Issue by ddugovic** [ProAlgos/ProAlgos-Cpp#367]
GitHub automates builds on every commit (free for open source projects):
https://github.com/features/actions

**Comment by alxmjo** [comment]
Thanks for this. Could you explain the benefit of using this system over our existing Travis CI system?

**Comment by ddugovic** [comment]
Developers who fork this project would not need to create Travis accounts or create pull requests to observe test results for their forks.  (Of course Travis CI has many advantages, however it is possible to use both systems.)

**Comment by alxmjo** [comment]
Thanks for this! Merged.
