### ISSUE TITLE
Linked list data structure implementation in c is missing

### ISSUE THREAD

**Issue by syedareehaquasar** [ProAlgos/ProAlgos-Cpp#383]

**Comment by Srijan7777** [comment]
can i contribute to this?
I have to add more LL implementation and algorithms right?

**Comment by alxmjo** [comment]
Hi @syedareehaquasar and @Srijan7777. You don't see a linked list data structure in C because this repository is focused on C++. Perhaps there's another data structure or algorithm you'd like to contribute? If so, please don't hesitate to open a new issue to discuss.
