### ISSUE TITLE
Documentation for Binary Search Tree

### ISSUE THREAD

**Issue by PhysicsUofRAUI** [ProAlgos/ProAlgos-Cpp#392]
Hi. I want to add the documentation for the binary search tree.

**Comment by alxmjo** [comment]
Great! Let me know if you have any questions.

**Comment by PhysicsUofRAUI** [comment]
I have a question about the space complexity of the iterative tree traversal vs the recursive tree traversal. It seems to me that they should be different, but in the comments in the hpp file, they are listed as the same.

**Comment by PhysicsUofRAUI** [comment]
I have created a pull request with this. I put in the documentation that the space complexity is O(1) for the insert, remove and search. I think that might be wrong since it is different than what was in the comments, but I am not sure why. 

Is it because the computer has to keep the whole tree in memory all the time or for some other reason? Sorry for my ignorance about space complexity.

**Comment by faheel** [comment]
@PhysicsUofRAUI You've got it right. The space complexity is O(1) since a constant amount of extra space is required by these operations. In the comments too the space complexity is O(1) for these operations.
