### ISSUE TITLE
Red-black trees

### ISSUE THREAD

**Issue by vaibhav2903** [ProAlgos/ProAlgos-Cpp#40]
I will implement the RedBlack trees and its important features

**Comment by yblank1** [comment]
I would like to work on this one. Should the tree only be able to handle ints?

**Comment by faheel** [comment]
@yblank1 Sure you can!

> Should the tree only be able to handle ints?

It would be better if it's generic (templated), which would enable it to handle any data type for which the comparison operators are already defined (such as all the built-in types).

**Comment by psarvesh** [comment]
@faheel Is this under development by anyone? (No pull requests)

If no one is working on this, I will take this up.

**Comment by faheel** [comment]
@psarvesh Doesn't look like anyone's working on it, so you can 👍

**Comment by faheel** [comment]
Closing this since there haven't been any updates for a long time. Please open a new issue if you'd like to work on red-black trees.
