### ISSUE TITLE
Add Exponential search

### ISSUE THREAD

**Issue by nandiniagrawal2000** [ProAlgos/ProAlgos-Cpp#412]
Exponential search  is a crucial searching algorithm and I would like to add it.

**Comment by anishsingh935** [comment]
can you please confirm me that weather this issues is open or closed??
 so that I can contribute if open !

**Comment by nandiniagrawal2000** [comment]
I have already made a pull request for this issue.

**Comment by anishsingh935** [comment]
ok 
thanks
