### ISSUE TITLE
add segment tree data structure 

### ISSUE THREAD

**Issue by dhnanj2** [ProAlgos/ProAlgos-Cpp#422]
Segment tree is a powerful DS to support range queries in an efficient way.
know more about it here : https://cp-algorithms.com/data_structures/segment_tree.html
I would love to contribute it to this project and close this issue.

**Comment by Priyanshi-Chauhan** [comment]
Segment tree is a great tool in competitive programming and is very efficient in range queries. I have some good codes and knowledge to contribute. Perhaps come up with great solutions. 
Can I contribute to this issue?
