### ISSUE TITLE
Primorial

### ISSUE THREAD

**Issue by faheel** [ProAlgos/ProAlgos-Cpp#43]
Implement an algorithm for calculating the [primorial](https://en.wikipedia.org/wiki/Primorial) of a given prime number _P<sub>n</sub>_

**Comment by janos-laszlo** [comment]
In the reference that you gave there are two definitions, which one should I use?
Pn should symbolize the first n prime numbers, or the prime numbers less than Pn?

**Comment by faheel** [comment]
**P<sub>n</sub>** is the given prime number whose primorial, **P<sub>n</sub>#**, is to be calculated.
The input can be taken in any one of the following ways:
1. Input the value of *P<sub>n</sub>*
1. Input the value of *n*

But the result should be the value of *P<sub>n</sub>#*.

**Comment by janos-laszlo** [comment]
Should I also validate the user input for option 1? In other words to check if Pn is prime.

**Comment by faheel** [comment]
Yes, P<sub>n</sub> needs to be checked to be prime.

**Comment by yashbansal6** [comment]
Hope you don;t mind if I started working on this issue

**Comment by AlphaQ52** [comment]
I will work on this

**Comment by darelover** [comment]
@faheel I am interested in working on this. Do you mind assigning me this issue? Also, I have few doubts:
> The input can be taken in any one of the following ways:
> 1. Input the value of Pn
> 2. Input the value of n

Should i implement two header files, one for each? or should i implement two functions in one header file only?

**Comment by JisooBrianKim** [comment]
Hi I would like to work on this

**Comment by naveensaigit** [comment]
Hi, could I work on this issue?

**Comment by sdorbala** [comment]
Hey, I have a working algorithm for this. Can I raise a PR for this?

**Comment by alxmjo** [comment]
Lots of interest in this issue. Anyone should feel free to give it a try.
