### ISSUE TITLE
Euler Totient function

### ISSUE THREAD

**Issue by knotman90** [ProAlgos/ProAlgos-Cpp#55]
What about writing some code for computing the euler totient function?

It is defined as follows:
Given an integer `n` how many number `<n` are coprime with it?

It is a very common constant in number theory.

https://en.wikipedia.org/wiki/Euler%27s_totient_function

Would you mind if I submit a PR on this?

**Comment by faheel** [comment]
@knotman90 Yes, you can definitely submit a PR for this. In fact I was thinking about adding it a few weeks ago but didn't get the time.

You can add the code in a file named `EulerTotient.cpp` in the `NumberTheory` folder.

**Comment by ankur54** [comment]
Is the issue open? I would like to work on it

**Comment by knotman90** [comment]
@ankur54  I guess you can as I have not performed any action since then.

**Comment by ankur54** [comment]
Should the Header file be .h or .hpp file?

**Comment by ankur54** [comment]
Would a normal c++ code suffice or, do I have to code it in .h file?

**Comment by alxmjo** [comment]
Algorithm implementation goes in header (.hpp) file, unit tests go in .cpp file. Thanks!

**Comment by faheel** [comment]
Since the recent code reorganisation, the code for this should now go in `include/algorithm/number_theory/euler_totient.hpp`.

**Comment by naveensaigit** [comment]
Can I work on this?

**Comment by knotman90** [comment]
Yes please. Make a pull request.
