### ISSUE TITLE
Sudoku Solver using Backtracking 

### ISSUE THREAD

**Issue by sriram-25** [ProAlgos/ProAlgos-Cpp#60]
I would like to add a program for solving Sudoku using backtracking.

**Comment by faheel** [comment]
@sriram-25 You can add the Sudoku solver to `Sudoku.cpp` in the `Backtracking` folder.

And for graph algorithms, I'll soon add the graph data structure (both directed and undirected) which you and others can use to implement graph algorithms.

**Comment by ankur54** [comment]
Is this issue still open? I would like to contribute to it
