### ISSUE TITLE
Bucket sort

### ISSUE THREAD

**Issue by ritwik12** [ProAlgos/ProAlgos-Cpp#63]
Hey, 
Bucket sort is not included . I would like to include it too.
Also according to issue #36 radix sort is still not there, I would like to add that too.

**Comment by Rajiv2605** [comment]
Can I contribute to this? This would be first open source contribution and it would be great if you could tell me how to go about it.

**Comment by ritwik12** [comment]
BucketSort is already contributed by me with PR #64 . You may work on Radix sort.

**Comment by Rajiv2605** [comment]
Okay, I will do the Radix Sort.

**Comment by Rajiv2605** [comment]
I have submitted a pull request named "Created Radix Sort" with the Radix Sort code. Please review it.

**Comment by ritwik12** [comment]
@faheel  is the owner of this repository. He will review and merge it @Rajiv2605 .  
:)

**Comment by ritwik12** [comment]
@faheel  is the owner of this repository, So only he can review and merge it @Rajiv2605 :)

**Comment by ritwik12** [comment]
Closing being unappropriated.
