### ISSUE TITLE
make algorithms generic (templated)

### ISSUE THREAD

**Issue by cppxor2arr** [ProAlgos/ProAlgos-Cpp#69]
I notice it seems like all the functions that implement algorithms take in a specific container as part of the argument (std::vector it seems like). I think these functions should be templated and made generic. If the container cannot be worked on by the function then a compile error should occur.

**Comment by pythagoraskitty** [comment]
I would be interested in trying to help.  May I please have a try?

Thanks,
pythagoraskitty

**Comment by cppxor2arr** [comment]
Yes, you could try and create a pull request. While templating the functions some `std::vector` specific member functions might need to be changed to be more generic. I would help, but right now I have to study for tests.

**Comment by pythagoraskitty** [comment]
Thank you!  I'll give it a go!

**Comment by cppxor2arr** [comment]
Next time, keep in mind faheel is the owner of this repository. Not me.

**Comment by OndraSlejtr** [comment]
Is there anyone working on this currently? Can I give it a go?

**Comment by faheel** [comment]
## Note
All those interested in taking this up, please note that after the currently active PRs are dealt with, in order to proceed with #74, the project files will be reorganised and refactored. It would be better if this issue is dealt with once that process is complete.

**Comment by faheel** [comment]
Issue #74 is now closed
