### ISSUE TITLE
Linked list algorithms

### ISSUE THREAD

**Issue by sarfrazbaig** [ProAlgos/ProAlgos-Cpp#72]
There is no linked list data structure present here. Can I add some commonly used linked list algorithms like reversing a linked list, floyd-cycle finding algortithm etc.

**Comment by faheel** [comment]
@sarfrazbaig Issue #34 is about linked lists, related to which there is PR #39 which is under review. Once it gets merged, you can use it to add related algorithms if you are interested :)

**Comment by ankur54** [comment]
Is this issue open? I would like to contribute to it!

**Comment by ghost** [comment]
Many algorithms for linked lists are still not there; I would like to contribute; so where should I put those algorithms under the reorganise branch?

**Comment by faheel** [comment]
[Singly linked list](https://github.com/faheel/Algos/blob/reorganise/C%2B%2B/include/data_structures/singly_linked_list.cpp) has already been implemented in the `reorganise` branch, and there are two open PRs for doubly linked lists. So anyone looking to contribute algorithms for singly linked list can do so by creating a PR against the `reorganise` branch.

**Comment by ghost** [comment]
> [Singly linked list](https://github.com/faheel/Algos/blob/reorganise/C%2B%2B/include/data_structures/singly_linked_list.cpp) has already been implemented in the `reorganise` branch, and there are two open PRs for doubly linked lists. So anyone looking to contribute algorithms for singly linked list can do so by creating a PR against the `reorganise` branch.

So, should I add a new file named 'Algorithms on Singly Linked List' or something like that?
@faheel ?

**Comment by faheel** [comment]
@jsahil730 You can implement it in a header file in `C++/include/data_structure/linked_list/singly_linked_list.hpp`

**Comment by ghost** [comment]
@faheel  @alxmjo Please help me with an issue - I am having problems in implementing few algorithms on Linked Lists - for example Cycle finding algorithms can't be implemented with the given implementation of linked list as having both head, tail and length - A list whch has loop will have infinite size, so it can't be made with the shown implementation - and hence, the above algos become useless. What should I do then? Should I change the implementation, should I move ahead from such algos; what to do?

**Comment by faheel** [comment]
@jsahil730 Adding a constant member function, say `get_head`, to the `SinglyLinkedList` class that returns a constant copy of the `head` pointer should enable you to implement the cycle detection algorithm.

The following should work (though I haven't tested it yet):

```cpp
template<typename T>
const Node<T>* const SinglyLinkedList::get_head() const {
    // returns a constant copy of `head` that is a constant pointer to the underlying `Node`
    return head;
}
```

(To understand what `const Node<T>* const` means, read it right to left: "constant pointer to a `Node<T>` that is constant").

**Comment by alxmjo** [comment]
Note that we now have [singly linked list](https://github.com/faheel/Algos/blob/master/C%2B%2B/include/data_structure/linked_list/singly_linked_list.hpp) and [doubly linked list](https://github.com/faheel/Algos/blob/master/C%2B%2B/include/data_structure/linked_list/doubly_linked_list.hpp) data structures.
