### ISSUE TITLE
Median in a stream of integers

### ISSUE THREAD

**Issue by SKAUL05** [ProAlgos/ProAlgos-Cpp#79]
I would like to add an algorithm that calculates the median in a stream of running integers.
Time Complexity:O(N^2)

**Comment by faheel** [comment]
Can you please explain what a "stream of running integers" means? I take it that it's different from simply a container (`array`, `vector`, `set` etc.) of integers.

**Comment by SKAUL05** [comment]
We would be given a number containing the number of integers to follow. Taking input of every integer we have to print the median of current set of integers.
e.g when reading 1st element say 5-> median=5
when reading 2nd element say 25-> median =25
when reading 3rd element say 12-> median =12.
like so on... 
We will take a vector to push integers sequentially.

**Comment by faheel** [comment]
Thanks for the clarification! It would be nice to have it in repo.
But I think the time complexity should be **_O_**(N * log(N)). If you use a `std::set` or a `std::multiset`, each insertion will be an **_O_**(log(N)) operation. Then finding the median will be an **_O_**(1) operation as you would simply return the element at index `set.size() / 2` (or the average of `set.size() / 2` and `set.size() / 2 + 1` if the size is even).
So for a total of `N` numbers, the overall time complexity will be:
log(1) + log(2) + log(3) + ... + log(N)
= log(N!)
= **_O_**(N * log(N)), or to be more accurate, **_Θ_**(N * log(N)).

**Comment by SKAUL05** [comment]
Yeah it is O(N * log(N)) but i am using a vector and then inserting new element by finding upper_bound as the stream needs to be in increasing order.

**Comment by faheel** [comment]
Using a set or multiset would be simpler and more efficient. Then why use a vector?

**Comment by SKAUL05** [comment]
There is no specific point to use vectors but i'm much more familiar with vectors and since both have same time complexities i preferred vectors.

**Comment by faheel** [comment]
> [...] since both have same time complexities [...]

Only if the stream is in increasing order. Using a multiset, this constraint will be eliminated. And having less constraints is more preferable :)

I would suggest reading up on [`std::multiset`](http://en.cppreference.com/w/cpp/container/multiset) and using it to implement the algorithm. [`std::advance`](http://en.cppreference.com/w/cpp/iterator/advance) will also be of help in accessing element by index in a multiset.

**Comment by SKAUL05** [comment]
The stream is not in increasing order. The stream can be in any order we have to arrange it in increaing order so as to find the median. Only assumption is that there are no duplicates.

**Comment by faheel** [comment]
If the stream is not in increasing order, using a multiset will be more efficient (**_O_**(N * log(N)) vs a vector (**_O_**(N^2)).

**Comment by SKAUL05** [comment]
Okay i will look into it.

**Comment by SKAUL05** [comment]
Hey, I found out a solution to this problem using Heaps. Should I implement it.

**Comment by faheel** [comment]
If its implementation is as simple as, or much simpler than using a `multiset`, and is as efficient (**_O_**(N * log(N) time and **_O_**(N) space), then sure, you can implement it using heaps.

**Comment by SKAUL05** [comment]
Hey how should i submit my implementation.

**Comment by faheel** [comment]
### Here are the steps:
1. Fork the repo to create your own copy
1. Clone your copy to your computer
1. Create a branch, giving it some suitable, but short, name (eg. `stream-median`)
1. Create folders, add code and tests etc.
1. Push the changes to GitHub
1. From your copy on GitHub, you can submit a pull request. Submit it towards the `master` branch.

**Comment by ayushagg31** [comment]
Hi, master, I would like to present you my code link for review, if you think it's good enough for contribution, then tell me, I will send a PR for the same.Here is code link:https://github.com/ayushagg31/codelick/blob/master/DSA/Random-Algorithms/median_from_datastream.C

Also if you can review my repo and tell me about which algo I can contribute from this repo of mine [https://github.com/ayushagg31/codelick/tree/master/DSA](URL). that would be great help/

**Comment by faheel** [comment]
As I have mentioned in other issues that are `On hold`, please wait until issue #74 is closed before sending your pull request.

**Comment by faheel** [comment]
Issue #74 is now closed

**Comment by eskeype** [comment]
Has anyone completed this algorithm yet? If not I would like to take it
