### ISSUE TITLE
Point QuadTree

### ISSUE THREAD

**Issue by ShumWengSang** [ProAlgos/ProAlgos-Cpp#84]
I see that there are no point quad tree implementation here. Can I give it a go?

**Comment by faheel** [comment]
Quadtree seems like a cool data structure! I didn't know about it before, so thanks for suggesting it :+1:
And yes, you can add it, but please wait until issue #74 is closed.

**Comment by ShumWengSang** [comment]
Hi are there anywhere where I can read up on how to get the Time complexity and Space complexity of my functions? I have no idea how to get these...

**Comment by faheel** [comment]
1. Read this [HackerEarth tutorial](https://www.hackerearth.com/practice/basic-programming/complexity-analysis/time-and-space-complexity/tutorial/) on time and space complexity
1. Read the [Wikipedia article](https://en.wikipedia.org/wiki/Time_complexity) on time complexity
1. Read these University of Texas [lecture notes](https://www.cs.utexas.edu/users/djimenez/utsa/cs1723/lecture2.html) on time and space complexity
1. If you still need to learn more, search for more articles or watch some YouTube videos regarding "finding time complexity", "determining time complexity" etc.

**Comment by faheel** [comment]
Issue #74 is now closed
