### ISSUE TITLE
Median from datastream code for review

### ISSUE THREAD

**Issue by ayushagg31** [ProAlgos/ProAlgos-Cpp#86]
Hi, master, I would like to present you my code link for review, if you think it's good enough for contribution, then tell me, I will send a PR for the same.Here is code link:https://github.com/ayushagg31/codelick/blob/master/DSA/Random-Algorithms/median_from_datastream.C

Also if you can review my repo and tell me about which algo I can contribute from this repo of mine https://github.com/ayushagg31/codelick/tree/master/DSA. that would be great help/

**Comment by faheel** [comment]
@ayushagg31 Thank you for your interest in contributing to the repo! An issue regarding "median of a stream of values" already exists as issue #79. **Comment on that issue to follow up this conversation**.

You can contribute implementations of any algorithm or data structure you seem fit. However, before sending the pull request make sure that your code:
- is C++14 compliant and uses modern C++ features wherever useful and/or necessary,
- adheres to the [C++ Coding Guidelines](../blob/master/C%2B%2B_CODING_GUIDELINES.md) of this repo (which are adapted from the [Google C++ Style Guide](https://google.github.io/styleguide/cppguide.html)),
- doesn't give any warning or errors when compiled using a C++14 compliant compiler with all warnings enabled (brownie points for `-Wextra` :wink:).

Also, you need to accompany your code with **test code** that checks for base cases, normal cases, edge cases etc. We use the amazing testing framework called [Catch](https://github.com/philsquared/Catch) for writing unit tests.
