### ISSUE TITLE
Matrix Chain Multiplication

### ISSUE THREAD

**Issue by ashvinlohiya** [ProAlgos/ProAlgos-Cpp#87]
Given n matrices A1, A2, ..., An, to be multiplied, determine how to parenthesize the matrices to minimize the total number of multiplications.

(This would be my first contribution, so I had some questions, and also would it work if I code it in Java? Thanks :) )

**Comment by faheel** [comment]
@ashvinlohiya Thanks for the suggestion! Having this in the repo would be great :+1:

You are very much welcome to contribute, but please note that I intend to use continuous integration in the project as mentioned in issue #74. So the whole project will be restructured and so I suggest that you wait until issue #74 is closed before contributing.

If you intend to submit code in other languages like Java, it's fine. But note that you would also need to add unit tests accompanying your code, and so a testing framework needs to be decided beforehand. If you know of one and would like to recommend, then please do.

**Comment by ashvinlohiya** [comment]
Thank you for reaching out! This is my first go at Open Source, so nope, I do not have any recommendation. If you know / suggest a framework, I'm happy to look into it and see if I can work with it? :)

**Comment by faheel** [comment]
You may check out [JUnit](http://junit.org/junit4/).

**Comment by faheel** [comment]
Issue #74 is now closed

**Comment by khushman1** [comment]
Hi, this seems to be open, and I'll begin working on it.
Where should I create the file @faheel ? `source/dynamic_programming/matrix_multiplication.cpp`?

**Comment by faheel** [comment]
@khushman1 That's right. The source file should be created as `source/dynamic_programming/matrix_multiplication.cpp` and the unit test as `test/dynamic_programming/matrix_multiplication.test.cpp`

**Comment by faheel** [comment]
Closed in #105
