### ISSUE TITLE
Depth First Search

### ISSUE THREAD

**Issue by ashvinlohiya** [ProAlgos/ProAlgos-Cpp#88]
I couldn't find if DFS is done before, if not, I could totally do that. (In java if possible)
Thanks

**Comment by faheel** [comment]
Issue #74 is now closed

**Comment by swap-pakhare** [comment]
Can I take this up?

**Comment by commit2gaming** [comment]
Hello Faheel, I'm learning C++ and I would like to contribute to your project.
Is this issue still open? If not, can you suggest me another easy one?
Thanks
