### ISSUE TITLE
Diameter of a tree using BFS/DFS

### ISSUE THREAD

**Issue by ayushagg31** [ProAlgos/ProAlgos-Cpp#89]
Just suggesting, you can add this one too in your repo.

**Comment by faheel** [comment]
Yes, that would be good. I'll add it once the Tree class and the implementations of BFS and DFS are added. Thanks for the suggestion!

**Comment by ayushagg31** [comment]
Adding similar problem link in code of algorithm for better understanding is also helpful and pls reply for the issue #86
