### ISSUE TITLE
Priority Queue implementation using heaps.

### ISSUE THREAD

**Issue by kuldipkumark** [ProAlgos/ProAlgos-Cpp#91]
I would like to contribute the priority queue implementation using heaps.
With operations like insert, getmaxpriority, delmaxpriority.

**Comment by faheel** [comment]
Sure, that would be good! But please wait until issue #74 is closed.

**Comment by faheel** [comment]
Issue #74 is now closed

**Comment by rsarky** [comment]
Can I take up this issue if noone is working on it?
