### ISSUE TITLE
Merging two Binary Search Trees

### ISSUE THREAD

**Issue by SKAUL05** [ProAlgos/ProAlgos-Cpp#96]
I would like to add an algorithm to merge two balanced Binary Search Trees in O(M+N) time, where M is number of nodes in first tree and N is number of nodes in second tree.

**Comment by YashAndonia** [comment]
#Algorithm for merging the two binary search trees, using a single common root node creation
 #[bin_tree_combiner_algo.txt](https://github.com/faheel/Algos/files/1799701/bin_tree_combiner_algo.txt)

**Comment by sarcastic-noob** [comment]
I would like to work on this issue.
