### ISSUE TITLE
Edit distance algorithm

### ISSUE THREAD

**Issue by karndubey** [ProAlgos/ProAlgos-Cpp#97]
I would like to implement edit distance algorithm for strings

**Comment by faheel** [comment]
Sure! Create a file named `edit_distance.hpp` under `C++/include/algorithm/string/`, and for the unit test `edit_distance.cpp` under `C++/test/algorithm/string/`

**Comment by anand434** [comment]
can I add it, it's been not added yet!

**Comment by faheel** [comment]
@karndubey Have you made some progress on this?

@anand434 You can give it a go if you're interested.

**Comment by karndubey** [comment]
@faheel I have written the code I need to write unit test and merge the code

**Comment by anand434** [comment]
@faheel and @karndubey can you explain me how to do unit test.

**Comment by faheel** [comment]
@karndubey Good going!

@anand434 You can help me review the code once @karndubey submits the PR. Until then you are welcome to contribute to another issue :smiley:

**Comment by anand434** [comment]
@faheel thanks

**Comment by sumit9696** [comment]
Is it done? Or can i do it?

**Comment by faheel** [comment]
This was taken up by someone but was later abandoned. So, anyone who's interested in implementing it can take this up.

**Comment by sumit9696** [comment]
I want to do this.

**Comment by alxmjo** [comment]
@sumit9696 Thanks for your interest! Please read our [Contributing Guidelines](https://github.com/faheel/Algos/blob/master/CONTRIBUTING.md) before you start writing the code. Once you've done that, add the code as a file named `edit_distance.hpp` under `C++/include/algorithm/string/`, and for the unit test `edit_distance.cpp` under `C++/test/algorithm/string/`. If you get stuck somewhere, or need some clarification on a topic, feel free to ask questions here or on Gitter.

**Comment by sumit9696** [comment]
Thanks. Assign me this issue..I will start working on it now

**Comment by sumit9696** [comment]
In the unit test, it is mentioned that I need to make .cpp file which is the source file, but you told me to make .hpp file. Can u please help me in this?

**Comment by alxmjo** [comment]
Definitely. The source code, which actually implements the edit distance algorithm, will go in the `.hpp` file. The unit tests for that algorithm will go in the `.cpp` file. To see what I'm talking about, check out binary search on the `reorganise` branch:
- [Binary search **implementation** (as `.hpp` file) in `/include/algorithm/searching/`](https://github.com/faheel/Algos/blob/reorganise/C%2B%2B/include/algorithm/searching/binary_search.hpp)
- [Binary search **unit tests** (as `.cpp` file) in `/test/algorithm/searching/`](https://github.com/faheel/Algos/blob/reorganise/C%2B%2B/test/algorithm/searching/binary_search.cpp)

Does that make sense?

**Comment by sumit9696** [comment]
Yes thanks and I will look into it and let you know.

**Comment by sumit9696** [comment]
When I am doing make test, it is producing nothing. Why is it happening can u help?

**Comment by alxmjo** [comment]
@sumit9696 Someone else is discussing this same issue with Faheel right now on Gitter. Have a look: https://gitter.im/Algos-f/Lobby?source=orgpage

Basically there are two ways of compiling the project and running tests, Make and CMake (which generates makefiles). The `make test` command corresponds to the makefile, whereas the project reorganisation is adding tests into CMake. Faheel knows more about that than I do, which is why I'm referring you to the chat.

**Comment by sumit9696** [comment]
Thanks, I will look at it.

**Comment by faheel** [comment]
@sumit9696 Sorry about the docs not having the complete information about adding and running tests. I'll update them.

**Comment by faheel** [comment]
Implemented in #193.
